### ISSUE TITLE
path

### ISSUE THREAD

**Issue by jschoch** [andypugh/LatheMacros#1]
is there a clear way to install this under a folder, or do I need to dump all the files into the dir with my .ini?  It is complaining about a bunch of the svg files and saying:

```
Waiting for component 'lathemacro' to become ready.
While waiting for 'lathemacro', component 'gladevcp' loaded.
did you specify the correct name via 'loadusr -Wn'?............
```

my ini 

```
[DISPLAY]
EMBED_TAB_NAME=Cycles
EMBED_TAB_COMMAND = halcmd loadusr -Wn lathemacro gladevcp -c gladevcp -U notouch=1 -U norun=0 -u ./lathemacro/LatheMacros/lathehandler.py -x {XID} ./lathemacro/LatheMacros/lathemacro.ui
```

Also, your readme says `loadusr -Wn gladevcp gladevcp ...` but in the forums you say it should be like above.

happy to fork and PR updated readme with these details.

**Comment by andypugh** [comment]
The G-code subs should all work anywhere in SUBROUTINE_PATH, though I think it is better to keep them out of linuxcnc/nc_files to avoid the risk of them being accidentally tidied away. 
```
[RS274NGC]
...
SUBROUTINE_PATH = LatheMacros
```
The other commands all seem to execute in the context of the INI file location, so you would need to give the EMBED_TAB_COMMAND paths relative to that, for example:
```
MBED_TAB_COMMAND= gladevcp -c gladevcp -u LatheMacros/lathehandler.py -x {XID} LatheMacros/lathemacro.ui
```
And then one final change, unfortunately, to a hardcoded path in line 118 of "lathehandler.py"
```
        self.svg = Rsvg.Handle().new_from_file('LatheMacros/LatheMacro.svg')
```
I have tested this in a sim, and it seems to work, as far as I could test on my dev machine (with no hardware)

**Comment by jschoch** [comment]
Thanks!  This worked Closing.  If you want me to mess with the docs via a PR just let me know.

**Comment by andypugh** [comment]
How's your Python? 
That change to the handler file could probably use
```
os.path.dirname( __file__)
```
to guess the path to the SVG. Or we could add another option like --svg-path

**Comment by jschoch** [comment]
my python is terrible!  My first program was a virtual shaper simulator for making gears on an A-Axis, and my 2nd program is a system for golf swing analysis using AI pose estimation and high speed video.

But, I do really want to save a pick list of defaults for something like feed/rev and depth of cut.  I opened another issue about glade not opening the .ui file, there are 100's of errors....  But if I can get it editable I want to take a crack at both the path fix and some defaults/save previous state/picklists.

**Comment by andypugh** [comment]
See the v3.1 release for an easier way to relocate. 
(mainly 684888079130efb11576bfa8e2322b99fdafa080)
