### ISSUE TITLE
glade editing the UI  EMC_Action_MDI not found

### ISSUE THREAD

**Issue by jschoch** [andypugh/LatheMacros#2]
I wanted to hardcode some text because the tool tips are a bit slow and I don't plan on using this everyday and likely will forget what the boxes are.... Anyway, when I load the ui in glade I get "EMC_Action_MDI" errors all over.

`Object has unrecognized type EMC_Action_MDI`

This is odd, but I also get some oddball issues in Axis so maybe I'm missing some stuff.  I see EMC_Action_MDI in the /usr/share/glade3/catalogs/hal_python.xml file...

I was able to build a little glade panel so I don't quite know what this error is since google search for 'linuxcnc "object has unrecognized type EMC_Action_MDI"'  returns 0 results.

**Comment by andypugh** [comment]
Can you start linuxcnc from the command-line and paste all the startup messages here?
I have a fix in the pipeline for a problem with --no-run, but I think what you are describing is a little different.

**Comment by jschoch** [comment]
the issue i'm having is starting up glade and loading the ui file, not linuxcnc.  

In linux cnc I do get a bunch of errors for like 0 height or something, they stop when I click on the tab in axis.

**Comment by andypugh** [comment]
Maybe try installing the linuxcnc-
uspace-dev package. (If you haven't already)

**Comment by jschoch** [comment]
that was installed, poking this today a bit to try to see if I can fix it.

**Comment by jschoch** [comment]
found it, because i'm in wayland i needed this `export PYOPENGL_PLATFORM="x11"`  along with `export GDK_BACKEND="x11"` which was already in my profile.
